### ISSUE TITLE
add arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [TimWolla/docker-spiped#19]
I was build this image on arm64 architecture and successed. I found it can be support arm64 at https://github.com/docker-library/official-images/blob/master/library/spiped , So I think we can add it to the https://hub.docker.com/u/arm64v8/ . thanks

**Comment by TimWolla** [comment]
@longquan7 I don't have access to the arm64v8 user on Docker Hub. I don't even know who has. 

Pinging @tianon who is responsible for the official images for advice.

**Comment by tianon** [comment]
@TimWolla see https://github.com/docker-library/official-images#architectures-other-than-amd64, but especially https://github.com/docker-library/official-images#multiple-architectures :smile:

If your current `Dockerfile` compiles as-is on any of these other architectures with just a `FROM` change to add the proper arch namespace (which I'd imagine it probably does for most if not all of them, since it's a simple source compilation), then adding multiple architectures would be as simple as adding the `Architectures` field to `library/spiped`. :+1:

**Comment by tianon** [comment]
Oh, you already did exactly that in https://github.com/TimWolla/docker-spiped/commit/bbdc0d01ce890ae6f67c747814f8039bcdf02fa1.  Doh.  It's even already in `library/spiped`.  I'm slow this morning. :sweat_smile:

I'll go take a look and see if I can figure out what's going on with that build.

**Comment by tianon** [comment]
Doh, it's already long-since pushed, too: https://hub.docker.com/r/arm64v8/spiped/ (at least as far back as Aug 9)

This is already done. :face_with_thermometer: :innocent: :+1:

**Comment by longquan7** [comment]
@tianon @TimWolla That's great,thanks
